/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { BamlCtxManager, BamlRuntime, ClientRegistry, Image, } from "@boundaryml/baml"
import { type HTTPRequest, toBamlError } from '@boundaryml/baml';
import type TypeBuilder from './type_builder';
import type {
  AccessibilityReport,
  ContentStructure,
  SEOMetadata,
} from './types';

type BamlCallOptions = {
  tb?: TypeBuilder;
  clientRegistry?: ClientRegistry;
};

export class AsyncHttpRequest {
  constructor(
    private runtime: BamlRuntime,
    private ctxManager: BamlCtxManager,
  ) {}

  async AnalyzeAccessibility(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<HTTPRequest> {
    try {
      return await this.runtime.buildRequest(
        'AnalyzeAccessibility',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeAltText(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<HTTPRequest> {
    try {
      return await this.runtime.buildRequest(
        'AnalyzeAltText',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeArticleSchemaMarkup(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<HTTPRequest> {
    try {
      return await this.runtime.buildRequest(
        'AnalyzeArticleSchemaMarkup',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeContentClarity(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<HTTPRequest> {
    try {
      return await this.runtime.buildRequest(
        'AnalyzeContentClarity',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeContentStructure(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<HTTPRequest> {
    try {
      return await this.runtime.buildRequest(
        'AnalyzeContentStructure',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeContrast(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<HTTPRequest> {
    try {
      return await this.runtime.buildRequest(
        'AnalyzeContrast',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeDescriptiveAltText(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<HTTPRequest> {
    try {
      return await this.runtime.buildRequest(
        'AnalyzeDescriptiveAltText',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeEEAT(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<HTTPRequest> {
    try {
      return await this.runtime.buildRequest(
        'AnalyzeEEAT',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeFAQSchemaMarkup(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<HTTPRequest> {
    try {
      return await this.runtime.buildRequest(
        'AnalyzeFAQSchemaMarkup',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeFormAccessibility(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<HTTPRequest> {
    try {
      return await this.runtime.buildRequest(
        'AnalyzeFormAccessibility',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeH1Tag(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<HTTPRequest> {
    try {
      return await this.runtime.buildRequest(
        'AnalyzeH1Tag',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeHeadingHierarchy(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<HTTPRequest> {
    try {
      return await this.runtime.buildRequest(
        'AnalyzeHeadingHierarchy',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeHeadingStructure(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<HTTPRequest> {
    try {
      return await this.runtime.buildRequest(
        'AnalyzeHeadingStructure',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeKeyboardAccessibility(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<HTTPRequest> {
    try {
      return await this.runtime.buildRequest(
        'AnalyzeKeyboardAccessibility',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeMainSections(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<HTTPRequest> {
    try {
      return await this.runtime.buildRequest(
        'AnalyzeMainSections',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeSemanticElements(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<HTTPRequest> {
    try {
      return await this.runtime.buildRequest(
        'AnalyzeSemanticElements',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeSemanticTags(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<HTTPRequest> {
    try {
      return await this.runtime.buildRequest(
        'AnalyzeSemanticTags',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeUserIntent(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<HTTPRequest> {
    try {
      return await this.runtime.buildRequest(
        'AnalyzeUserIntent',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeWebsiteScreenshot(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<HTTPRequest> {
    try {
      return await this.runtime.buildRequest(
        'AnalyzeWebsiteScreenshot',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AssessWebpageImages(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<HTTPRequest> {
    try {
      return await this.runtime.buildRequest(
        'AssessWebpageImages',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async ExtractSEOMetadata(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<HTTPRequest> {
    try {
      return await this.runtime.buildRequest(
        'ExtractSEOMetadata',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async SuggestImprovements(
    seo: SEOMetadata,
    accessibility: AccessibilityReport,
    structure: ContentStructure,
    __baml_options__?: BamlCallOptions,
  ): Promise<HTTPRequest> {
    try {
      return await this.runtime.buildRequest(
        'SuggestImprovements',
        {
          seo: seo,
          accessibility: accessibility,
          structure: structure,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }
}

export class AsyncHttpStreamRequest {
  constructor(
    private runtime: BamlRuntime,
    private ctxManager: BamlCtxManager,
  ) {}

  async AnalyzeAccessibility(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<HTTPRequest> {
    try {
      return await this.runtime.buildRequest(
        'AnalyzeAccessibility',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeAltText(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<HTTPRequest> {
    try {
      return await this.runtime.buildRequest(
        'AnalyzeAltText',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeArticleSchemaMarkup(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<HTTPRequest> {
    try {
      return await this.runtime.buildRequest(
        'AnalyzeArticleSchemaMarkup',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeContentClarity(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<HTTPRequest> {
    try {
      return await this.runtime.buildRequest(
        'AnalyzeContentClarity',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeContentStructure(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<HTTPRequest> {
    try {
      return await this.runtime.buildRequest(
        'AnalyzeContentStructure',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeContrast(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<HTTPRequest> {
    try {
      return await this.runtime.buildRequest(
        'AnalyzeContrast',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeDescriptiveAltText(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<HTTPRequest> {
    try {
      return await this.runtime.buildRequest(
        'AnalyzeDescriptiveAltText',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeEEAT(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<HTTPRequest> {
    try {
      return await this.runtime.buildRequest(
        'AnalyzeEEAT',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeFAQSchemaMarkup(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<HTTPRequest> {
    try {
      return await this.runtime.buildRequest(
        'AnalyzeFAQSchemaMarkup',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeFormAccessibility(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<HTTPRequest> {
    try {
      return await this.runtime.buildRequest(
        'AnalyzeFormAccessibility',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeH1Tag(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<HTTPRequest> {
    try {
      return await this.runtime.buildRequest(
        'AnalyzeH1Tag',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeHeadingHierarchy(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<HTTPRequest> {
    try {
      return await this.runtime.buildRequest(
        'AnalyzeHeadingHierarchy',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeHeadingStructure(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<HTTPRequest> {
    try {
      return await this.runtime.buildRequest(
        'AnalyzeHeadingStructure',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeKeyboardAccessibility(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<HTTPRequest> {
    try {
      return await this.runtime.buildRequest(
        'AnalyzeKeyboardAccessibility',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeMainSections(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<HTTPRequest> {
    try {
      return await this.runtime.buildRequest(
        'AnalyzeMainSections',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeSemanticElements(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<HTTPRequest> {
    try {
      return await this.runtime.buildRequest(
        'AnalyzeSemanticElements',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeSemanticTags(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<HTTPRequest> {
    try {
      return await this.runtime.buildRequest(
        'AnalyzeSemanticTags',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeUserIntent(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<HTTPRequest> {
    try {
      return await this.runtime.buildRequest(
        'AnalyzeUserIntent',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeWebsiteScreenshot(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<HTTPRequest> {
    try {
      return await this.runtime.buildRequest(
        'AnalyzeWebsiteScreenshot',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AssessWebpageImages(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<HTTPRequest> {
    try {
      return await this.runtime.buildRequest(
        'AssessWebpageImages',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async ExtractSEOMetadata(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<HTTPRequest> {
    try {
      return await this.runtime.buildRequest(
        'ExtractSEOMetadata',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async SuggestImprovements(
    seo: SEOMetadata,
    accessibility: AccessibilityReport,
    structure: ContentStructure,
    __baml_options__?: BamlCallOptions,
  ): Promise<HTTPRequest> {
    try {
      return await this.runtime.buildRequest(
        'SuggestImprovements',
        {
          seo: seo,
          accessibility: accessibility,
          structure: structure,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }
}
