/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { BamlCtxManager, BamlRuntime, ClientRegistry, Collector, Image } from "@boundaryml/baml"
import { BamlStream, toBamlError } from '@boundaryml/baml';
import { AsyncHttpRequest, AsyncHttpStreamRequest } from './async_request';
import {
  DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX,
  DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME,
} from './globals';
import { LlmResponseParser, LlmStreamParser } from './parser';
import type { partial_types } from './partial_types';
import type TypeBuilder from './type_builder';
import type { RecursivePartialNull as MovedRecursivePartialNull } from './types';
import type {
  AccessibilityReport,
  AltTextReport,
  ArticleSchemaMarkupReport,
  ContentClarityReport,
  ContentStructure,
  ContrastReport,
  DescriptiveAltTextReport,
  EEATReport,
  FAQSchemaMarkupReport,
  FormAccessibilityReport,
  H1TagReport,
  HeadingHierarchyReport,
  HeadingStructureReport,
  ImprovementSuggestions,
  KeyboardAccessibilityReport,
  MainSectionsReport,
  SEOMetadata,
  SemanticElementsReport,
  SemanticTagReport,
  UserIntentReport,
  WebpageImagesReport,
  WebsiteScreenshotAnalysis,
} from './types';

/**
 * @deprecated Use RecursivePartialNull from 'baml_client/types' instead.
 */
export type RecursivePartialNull<T> = MovedRecursivePartialNull<T>;

type BamlCallOptions = {
  tb?: TypeBuilder;
  clientRegistry?: ClientRegistry;
  collector?: Collector | Collector[];
};

export class BamlAsyncClient {
  private runtime: BamlRuntime;
  private ctxManager: BamlCtxManager;
  private streamClient: BamlStreamClient;
  private httpRequest: AsyncHttpRequest;
  private httpStreamRequest: AsyncHttpStreamRequest;
  private llmResponseParser: LlmResponseParser;
  private llmStreamParser: LlmStreamParser;
  private bamlOptions: BamlCallOptions;

  constructor(
    runtime: BamlRuntime,
    ctxManager: BamlCtxManager,
    bamlOptions?: BamlCallOptions,
  ) {
    this.runtime = runtime;
    this.ctxManager = ctxManager;
    this.streamClient = new BamlStreamClient(runtime, ctxManager, bamlOptions);
    this.httpRequest = new AsyncHttpRequest(runtime, ctxManager);
    this.httpStreamRequest = new AsyncHttpStreamRequest(runtime, ctxManager);
    this.llmResponseParser = new LlmResponseParser(runtime, ctxManager);
    this.llmStreamParser = new LlmStreamParser(runtime, ctxManager);
    this.bamlOptions = bamlOptions || {};
  }

  withOptions(bamlOptions: BamlCallOptions) {
    return new BamlAsyncClient(this.runtime, this.ctxManager, bamlOptions);
  }

  get stream() {
    return this.streamClient;
  }

  get request() {
    return this.httpRequest;
  }

  get streamRequest() {
    return this.httpStreamRequest;
  }

  get parse() {
    return this.llmResponseParser;
  }

  get parseStream() {
    return this.llmStreamParser;
  }

  async AnalyzeAccessibility(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<AccessibilityReport> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = await this.runtime.callFunction(
        'AnalyzeAccessibility',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return raw.parsed(false) as AccessibilityReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeAltText(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<AltTextReport> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = await this.runtime.callFunction(
        'AnalyzeAltText',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return raw.parsed(false) as AltTextReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeArticleSchemaMarkup(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<ArticleSchemaMarkupReport> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = await this.runtime.callFunction(
        'AnalyzeArticleSchemaMarkup',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return raw.parsed(false) as ArticleSchemaMarkupReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeContentClarity(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<ContentClarityReport> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = await this.runtime.callFunction(
        'AnalyzeContentClarity',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return raw.parsed(false) as ContentClarityReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeContentStructure(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<ContentStructure> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = await this.runtime.callFunction(
        'AnalyzeContentStructure',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return raw.parsed(false) as ContentStructure;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeContrast(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<ContrastReport> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = await this.runtime.callFunction(
        'AnalyzeContrast',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return raw.parsed(false) as ContrastReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeDescriptiveAltText(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<DescriptiveAltTextReport> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = await this.runtime.callFunction(
        'AnalyzeDescriptiveAltText',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return raw.parsed(false) as DescriptiveAltTextReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeEEAT(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<EEATReport> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = await this.runtime.callFunction(
        'AnalyzeEEAT',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return raw.parsed(false) as EEATReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeFAQSchemaMarkup(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<FAQSchemaMarkupReport> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = await this.runtime.callFunction(
        'AnalyzeFAQSchemaMarkup',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return raw.parsed(false) as FAQSchemaMarkupReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeFormAccessibility(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<FormAccessibilityReport> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = await this.runtime.callFunction(
        'AnalyzeFormAccessibility',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return raw.parsed(false) as FormAccessibilityReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeH1Tag(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<H1TagReport> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = await this.runtime.callFunction(
        'AnalyzeH1Tag',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return raw.parsed(false) as H1TagReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeHeadingHierarchy(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<HeadingHierarchyReport> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = await this.runtime.callFunction(
        'AnalyzeHeadingHierarchy',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return raw.parsed(false) as HeadingHierarchyReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeHeadingStructure(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<HeadingStructureReport> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = await this.runtime.callFunction(
        'AnalyzeHeadingStructure',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return raw.parsed(false) as HeadingStructureReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeKeyboardAccessibility(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<KeyboardAccessibilityReport> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = await this.runtime.callFunction(
        'AnalyzeKeyboardAccessibility',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return raw.parsed(false) as KeyboardAccessibilityReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeMainSections(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<MainSectionsReport> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = await this.runtime.callFunction(
        'AnalyzeMainSections',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return raw.parsed(false) as MainSectionsReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeSemanticElements(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<SemanticElementsReport> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = await this.runtime.callFunction(
        'AnalyzeSemanticElements',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return raw.parsed(false) as SemanticElementsReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeSemanticTags(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<SemanticTagReport> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = await this.runtime.callFunction(
        'AnalyzeSemanticTags',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return raw.parsed(false) as SemanticTagReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeUserIntent(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<UserIntentReport> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = await this.runtime.callFunction(
        'AnalyzeUserIntent',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return raw.parsed(false) as UserIntentReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AnalyzeWebsiteScreenshot(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<WebsiteScreenshotAnalysis> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = await this.runtime.callFunction(
        'AnalyzeWebsiteScreenshot',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return raw.parsed(false) as WebsiteScreenshotAnalysis;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async AssessWebpageImages(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<WebpageImagesReport> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = await this.runtime.callFunction(
        'AssessWebpageImages',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return raw.parsed(false) as WebpageImagesReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async ExtractSEOMetadata(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): Promise<SEOMetadata> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = await this.runtime.callFunction(
        'ExtractSEOMetadata',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return raw.parsed(false) as SEOMetadata;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  async SuggestImprovements(
    seo: SEOMetadata,
    accessibility: AccessibilityReport,
    structure: ContentStructure,
    __baml_options__?: BamlCallOptions,
  ): Promise<ImprovementSuggestions> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = await this.runtime.callFunction(
        'SuggestImprovements',
        {
          seo: seo,
          accessibility: accessibility,
          structure: structure,
        },
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return raw.parsed(false) as ImprovementSuggestions;
    } catch (error) {
      throw toBamlError(error);
    }
  }
}

class BamlStreamClient {
  private runtime: BamlRuntime;
  private ctxManager: BamlCtxManager;
  private bamlOptions: BamlCallOptions;

  constructor(
    runtime: BamlRuntime,
    ctxManager: BamlCtxManager,
    bamlOptions?: BamlCallOptions,
  ) {
    this.runtime = runtime;
    this.ctxManager = ctxManager;
    this.bamlOptions = bamlOptions || {};
  }

  AnalyzeAccessibility(
    img: Image,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      collector?: Collector | Collector[];
    },
  ): BamlStream<partial_types.AccessibilityReport, AccessibilityReport> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = this.runtime.streamFunction(
        'AnalyzeAccessibility',
        {
          img: img,
        },
        undefined,
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return new BamlStream<
        partial_types.AccessibilityReport,
        AccessibilityReport
      >(
        raw,
        (a): partial_types.AccessibilityReport => a,
        (a): AccessibilityReport => a,
        this.ctxManager.cloneContext(),
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeAltText(
    img: Image,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      collector?: Collector | Collector[];
    },
  ): BamlStream<partial_types.AltTextReport, AltTextReport> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = this.runtime.streamFunction(
        'AnalyzeAltText',
        {
          img: img,
        },
        undefined,
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return new BamlStream<partial_types.AltTextReport, AltTextReport>(
        raw,
        (a): partial_types.AltTextReport => a,
        (a): AltTextReport => a,
        this.ctxManager.cloneContext(),
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeArticleSchemaMarkup(
    img: Image,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      collector?: Collector | Collector[];
    },
  ): BamlStream<
    partial_types.ArticleSchemaMarkupReport,
    ArticleSchemaMarkupReport
  > {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = this.runtime.streamFunction(
        'AnalyzeArticleSchemaMarkup',
        {
          img: img,
        },
        undefined,
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return new BamlStream<
        partial_types.ArticleSchemaMarkupReport,
        ArticleSchemaMarkupReport
      >(
        raw,
        (a): partial_types.ArticleSchemaMarkupReport => a,
        (a): ArticleSchemaMarkupReport => a,
        this.ctxManager.cloneContext(),
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeContentClarity(
    img: Image,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      collector?: Collector | Collector[];
    },
  ): BamlStream<partial_types.ContentClarityReport, ContentClarityReport> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = this.runtime.streamFunction(
        'AnalyzeContentClarity',
        {
          img: img,
        },
        undefined,
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return new BamlStream<
        partial_types.ContentClarityReport,
        ContentClarityReport
      >(
        raw,
        (a): partial_types.ContentClarityReport => a,
        (a): ContentClarityReport => a,
        this.ctxManager.cloneContext(),
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeContentStructure(
    img: Image,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      collector?: Collector | Collector[];
    },
  ): BamlStream<partial_types.ContentStructure, ContentStructure> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = this.runtime.streamFunction(
        'AnalyzeContentStructure',
        {
          img: img,
        },
        undefined,
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return new BamlStream<partial_types.ContentStructure, ContentStructure>(
        raw,
        (a): partial_types.ContentStructure => a,
        (a): ContentStructure => a,
        this.ctxManager.cloneContext(),
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeContrast(
    img: Image,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      collector?: Collector | Collector[];
    },
  ): BamlStream<partial_types.ContrastReport, ContrastReport> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = this.runtime.streamFunction(
        'AnalyzeContrast',
        {
          img: img,
        },
        undefined,
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return new BamlStream<partial_types.ContrastReport, ContrastReport>(
        raw,
        (a): partial_types.ContrastReport => a,
        (a): ContrastReport => a,
        this.ctxManager.cloneContext(),
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeDescriptiveAltText(
    img: Image,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      collector?: Collector | Collector[];
    },
  ): BamlStream<
    partial_types.DescriptiveAltTextReport,
    DescriptiveAltTextReport
  > {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = this.runtime.streamFunction(
        'AnalyzeDescriptiveAltText',
        {
          img: img,
        },
        undefined,
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return new BamlStream<
        partial_types.DescriptiveAltTextReport,
        DescriptiveAltTextReport
      >(
        raw,
        (a): partial_types.DescriptiveAltTextReport => a,
        (a): DescriptiveAltTextReport => a,
        this.ctxManager.cloneContext(),
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeEEAT(
    img: Image,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      collector?: Collector | Collector[];
    },
  ): BamlStream<partial_types.EEATReport, EEATReport> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = this.runtime.streamFunction(
        'AnalyzeEEAT',
        {
          img: img,
        },
        undefined,
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return new BamlStream<partial_types.EEATReport, EEATReport>(
        raw,
        (a): partial_types.EEATReport => a,
        (a): EEATReport => a,
        this.ctxManager.cloneContext(),
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeFAQSchemaMarkup(
    img: Image,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      collector?: Collector | Collector[];
    },
  ): BamlStream<partial_types.FAQSchemaMarkupReport, FAQSchemaMarkupReport> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = this.runtime.streamFunction(
        'AnalyzeFAQSchemaMarkup',
        {
          img: img,
        },
        undefined,
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return new BamlStream<
        partial_types.FAQSchemaMarkupReport,
        FAQSchemaMarkupReport
      >(
        raw,
        (a): partial_types.FAQSchemaMarkupReport => a,
        (a): FAQSchemaMarkupReport => a,
        this.ctxManager.cloneContext(),
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeFormAccessibility(
    img: Image,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      collector?: Collector | Collector[];
    },
  ): BamlStream<
    partial_types.FormAccessibilityReport,
    FormAccessibilityReport
  > {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = this.runtime.streamFunction(
        'AnalyzeFormAccessibility',
        {
          img: img,
        },
        undefined,
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return new BamlStream<
        partial_types.FormAccessibilityReport,
        FormAccessibilityReport
      >(
        raw,
        (a): partial_types.FormAccessibilityReport => a,
        (a): FormAccessibilityReport => a,
        this.ctxManager.cloneContext(),
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeH1Tag(
    img: Image,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      collector?: Collector | Collector[];
    },
  ): BamlStream<partial_types.H1TagReport, H1TagReport> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = this.runtime.streamFunction(
        'AnalyzeH1Tag',
        {
          img: img,
        },
        undefined,
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return new BamlStream<partial_types.H1TagReport, H1TagReport>(
        raw,
        (a): partial_types.H1TagReport => a,
        (a): H1TagReport => a,
        this.ctxManager.cloneContext(),
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeHeadingHierarchy(
    img: Image,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      collector?: Collector | Collector[];
    },
  ): BamlStream<partial_types.HeadingHierarchyReport, HeadingHierarchyReport> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = this.runtime.streamFunction(
        'AnalyzeHeadingHierarchy',
        {
          img: img,
        },
        undefined,
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return new BamlStream<
        partial_types.HeadingHierarchyReport,
        HeadingHierarchyReport
      >(
        raw,
        (a): partial_types.HeadingHierarchyReport => a,
        (a): HeadingHierarchyReport => a,
        this.ctxManager.cloneContext(),
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeHeadingStructure(
    img: Image,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      collector?: Collector | Collector[];
    },
  ): BamlStream<partial_types.HeadingStructureReport, HeadingStructureReport> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = this.runtime.streamFunction(
        'AnalyzeHeadingStructure',
        {
          img: img,
        },
        undefined,
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return new BamlStream<
        partial_types.HeadingStructureReport,
        HeadingStructureReport
      >(
        raw,
        (a): partial_types.HeadingStructureReport => a,
        (a): HeadingStructureReport => a,
        this.ctxManager.cloneContext(),
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeKeyboardAccessibility(
    img: Image,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      collector?: Collector | Collector[];
    },
  ): BamlStream<
    partial_types.KeyboardAccessibilityReport,
    KeyboardAccessibilityReport
  > {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = this.runtime.streamFunction(
        'AnalyzeKeyboardAccessibility',
        {
          img: img,
        },
        undefined,
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return new BamlStream<
        partial_types.KeyboardAccessibilityReport,
        KeyboardAccessibilityReport
      >(
        raw,
        (a): partial_types.KeyboardAccessibilityReport => a,
        (a): KeyboardAccessibilityReport => a,
        this.ctxManager.cloneContext(),
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeMainSections(
    img: Image,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      collector?: Collector | Collector[];
    },
  ): BamlStream<partial_types.MainSectionsReport, MainSectionsReport> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = this.runtime.streamFunction(
        'AnalyzeMainSections',
        {
          img: img,
        },
        undefined,
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return new BamlStream<
        partial_types.MainSectionsReport,
        MainSectionsReport
      >(
        raw,
        (a): partial_types.MainSectionsReport => a,
        (a): MainSectionsReport => a,
        this.ctxManager.cloneContext(),
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeSemanticElements(
    img: Image,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      collector?: Collector | Collector[];
    },
  ): BamlStream<partial_types.SemanticElementsReport, SemanticElementsReport> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = this.runtime.streamFunction(
        'AnalyzeSemanticElements',
        {
          img: img,
        },
        undefined,
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return new BamlStream<
        partial_types.SemanticElementsReport,
        SemanticElementsReport
      >(
        raw,
        (a): partial_types.SemanticElementsReport => a,
        (a): SemanticElementsReport => a,
        this.ctxManager.cloneContext(),
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeSemanticTags(
    img: Image,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      collector?: Collector | Collector[];
    },
  ): BamlStream<partial_types.SemanticTagReport, SemanticTagReport> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = this.runtime.streamFunction(
        'AnalyzeSemanticTags',
        {
          img: img,
        },
        undefined,
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return new BamlStream<partial_types.SemanticTagReport, SemanticTagReport>(
        raw,
        (a): partial_types.SemanticTagReport => a,
        (a): SemanticTagReport => a,
        this.ctxManager.cloneContext(),
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeUserIntent(
    img: Image,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      collector?: Collector | Collector[];
    },
  ): BamlStream<partial_types.UserIntentReport, UserIntentReport> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = this.runtime.streamFunction(
        'AnalyzeUserIntent',
        {
          img: img,
        },
        undefined,
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return new BamlStream<partial_types.UserIntentReport, UserIntentReport>(
        raw,
        (a): partial_types.UserIntentReport => a,
        (a): UserIntentReport => a,
        this.ctxManager.cloneContext(),
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeWebsiteScreenshot(
    img: Image,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      collector?: Collector | Collector[];
    },
  ): BamlStream<
    partial_types.WebsiteScreenshotAnalysis,
    WebsiteScreenshotAnalysis
  > {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = this.runtime.streamFunction(
        'AnalyzeWebsiteScreenshot',
        {
          img: img,
        },
        undefined,
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return new BamlStream<
        partial_types.WebsiteScreenshotAnalysis,
        WebsiteScreenshotAnalysis
      >(
        raw,
        (a): partial_types.WebsiteScreenshotAnalysis => a,
        (a): WebsiteScreenshotAnalysis => a,
        this.ctxManager.cloneContext(),
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AssessWebpageImages(
    img: Image,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      collector?: Collector | Collector[];
    },
  ): BamlStream<partial_types.WebpageImagesReport, WebpageImagesReport> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = this.runtime.streamFunction(
        'AssessWebpageImages',
        {
          img: img,
        },
        undefined,
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return new BamlStream<
        partial_types.WebpageImagesReport,
        WebpageImagesReport
      >(
        raw,
        (a): partial_types.WebpageImagesReport => a,
        (a): WebpageImagesReport => a,
        this.ctxManager.cloneContext(),
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  ExtractSEOMetadata(
    img: Image,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      collector?: Collector | Collector[];
    },
  ): BamlStream<partial_types.SEOMetadata, SEOMetadata> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = this.runtime.streamFunction(
        'ExtractSEOMetadata',
        {
          img: img,
        },
        undefined,
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return new BamlStream<partial_types.SEOMetadata, SEOMetadata>(
        raw,
        (a): partial_types.SEOMetadata => a,
        (a): SEOMetadata => a,
        this.ctxManager.cloneContext(),
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  SuggestImprovements(
    seo: SEOMetadata,
    accessibility: AccessibilityReport,
    structure: ContentStructure,
    __baml_options__?: {
      tb?: TypeBuilder;
      clientRegistry?: ClientRegistry;
      collector?: Collector | Collector[];
    },
  ): BamlStream<partial_types.ImprovementSuggestions, ImprovementSuggestions> {
    try {
      const options = { ...this.bamlOptions, ...(__baml_options__ || {}) };
      const collector = options.collector
        ? Array.isArray(options.collector)
          ? options.collector
          : [options.collector]
        : [];
      const raw = this.runtime.streamFunction(
        'SuggestImprovements',
        {
          seo: seo,
          accessibility: accessibility,
          structure: structure,
        },
        undefined,
        this.ctxManager.cloneContext(),
        options.tb?.__tb(),
        options.clientRegistry,
        collector,
      );
      return new BamlStream<
        partial_types.ImprovementSuggestions,
        ImprovementSuggestions
      >(
        raw,
        (a): partial_types.ImprovementSuggestions => a,
        (a): ImprovementSuggestions => a,
        this.ctxManager.cloneContext(),
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }
}

export const b = new BamlAsyncClient(
  DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME,
  DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX,
);
