/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { BamlCtxManager, BamlRuntime, ClientRegistry, } from "@boundaryml/baml"
import { toBamlError } from '@boundaryml/baml';
import type { partial_types } from './partial_types';
import type TypeBuilder from './type_builder';
import type {
  AccessibilityReport,
  AltTextReport,
  ArticleSchemaMarkupReport,
  ContentClarityReport,
  ContentStructure,
  ContrastReport,
  DescriptiveAltTextReport,
  EEATReport,
  FAQSchemaMarkupReport,
  FormAccessibilityReport,
  H1TagReport,
  HeadingHierarchyReport,
  HeadingStructureReport,
  ImprovementSuggestions,
  KeyboardAccessibilityReport,
  MainSectionsReport,
  SEOMetadata,
  SemanticElementsReport,
  SemanticTagReport,
  UserIntentReport,
  WebpageImagesReport,
  WebsiteScreenshotAnalysis,
} from './types';

export class LlmResponseParser {
  constructor(
    private runtime: BamlRuntime,
    private ctxManager: BamlCtxManager,
  ) {}

  AnalyzeAccessibility(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): AccessibilityReport {
    try {
      return this.runtime.parseLlmResponse(
        'AnalyzeAccessibility',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as AccessibilityReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeAltText(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): AltTextReport {
    try {
      return this.runtime.parseLlmResponse(
        'AnalyzeAltText',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as AltTextReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeArticleSchemaMarkup(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): ArticleSchemaMarkupReport {
    try {
      return this.runtime.parseLlmResponse(
        'AnalyzeArticleSchemaMarkup',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as ArticleSchemaMarkupReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeContentClarity(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): ContentClarityReport {
    try {
      return this.runtime.parseLlmResponse(
        'AnalyzeContentClarity',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as ContentClarityReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeContentStructure(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): ContentStructure {
    try {
      return this.runtime.parseLlmResponse(
        'AnalyzeContentStructure',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as ContentStructure;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeContrast(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): ContrastReport {
    try {
      return this.runtime.parseLlmResponse(
        'AnalyzeContrast',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as ContrastReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeDescriptiveAltText(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): DescriptiveAltTextReport {
    try {
      return this.runtime.parseLlmResponse(
        'AnalyzeDescriptiveAltText',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as DescriptiveAltTextReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeEEAT(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): EEATReport {
    try {
      return this.runtime.parseLlmResponse(
        'AnalyzeEEAT',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as EEATReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeFAQSchemaMarkup(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): FAQSchemaMarkupReport {
    try {
      return this.runtime.parseLlmResponse(
        'AnalyzeFAQSchemaMarkup',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as FAQSchemaMarkupReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeFormAccessibility(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): FormAccessibilityReport {
    try {
      return this.runtime.parseLlmResponse(
        'AnalyzeFormAccessibility',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as FormAccessibilityReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeH1Tag(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): H1TagReport {
    try {
      return this.runtime.parseLlmResponse(
        'AnalyzeH1Tag',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as H1TagReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeHeadingHierarchy(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): HeadingHierarchyReport {
    try {
      return this.runtime.parseLlmResponse(
        'AnalyzeHeadingHierarchy',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as HeadingHierarchyReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeHeadingStructure(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): HeadingStructureReport {
    try {
      return this.runtime.parseLlmResponse(
        'AnalyzeHeadingStructure',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as HeadingStructureReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeKeyboardAccessibility(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): KeyboardAccessibilityReport {
    try {
      return this.runtime.parseLlmResponse(
        'AnalyzeKeyboardAccessibility',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as KeyboardAccessibilityReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeMainSections(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): MainSectionsReport {
    try {
      return this.runtime.parseLlmResponse(
        'AnalyzeMainSections',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as MainSectionsReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeSemanticElements(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): SemanticElementsReport {
    try {
      return this.runtime.parseLlmResponse(
        'AnalyzeSemanticElements',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as SemanticElementsReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeSemanticTags(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): SemanticTagReport {
    try {
      return this.runtime.parseLlmResponse(
        'AnalyzeSemanticTags',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as SemanticTagReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeUserIntent(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): UserIntentReport {
    try {
      return this.runtime.parseLlmResponse(
        'AnalyzeUserIntent',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as UserIntentReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeWebsiteScreenshot(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): WebsiteScreenshotAnalysis {
    try {
      return this.runtime.parseLlmResponse(
        'AnalyzeWebsiteScreenshot',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as WebsiteScreenshotAnalysis;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AssessWebpageImages(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): WebpageImagesReport {
    try {
      return this.runtime.parseLlmResponse(
        'AssessWebpageImages',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as WebpageImagesReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  ExtractSEOMetadata(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): SEOMetadata {
    try {
      return this.runtime.parseLlmResponse(
        'ExtractSEOMetadata',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as SEOMetadata;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  SuggestImprovements(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): ImprovementSuggestions {
    try {
      return this.runtime.parseLlmResponse(
        'SuggestImprovements',
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as ImprovementSuggestions;
    } catch (error) {
      throw toBamlError(error);
    }
  }
}

export class LlmStreamParser {
  constructor(
    private runtime: BamlRuntime,
    private ctxManager: BamlCtxManager,
  ) {}

  AnalyzeAccessibility(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): partial_types.AccessibilityReport {
    try {
      return this.runtime.parseLlmResponse(
        'AnalyzeAccessibility',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.AccessibilityReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeAltText(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): partial_types.AltTextReport {
    try {
      return this.runtime.parseLlmResponse(
        'AnalyzeAltText',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.AltTextReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeArticleSchemaMarkup(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): partial_types.ArticleSchemaMarkupReport {
    try {
      return this.runtime.parseLlmResponse(
        'AnalyzeArticleSchemaMarkup',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.ArticleSchemaMarkupReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeContentClarity(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): partial_types.ContentClarityReport {
    try {
      return this.runtime.parseLlmResponse(
        'AnalyzeContentClarity',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.ContentClarityReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeContentStructure(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): partial_types.ContentStructure {
    try {
      return this.runtime.parseLlmResponse(
        'AnalyzeContentStructure',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.ContentStructure;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeContrast(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): partial_types.ContrastReport {
    try {
      return this.runtime.parseLlmResponse(
        'AnalyzeContrast',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.ContrastReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeDescriptiveAltText(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): partial_types.DescriptiveAltTextReport {
    try {
      return this.runtime.parseLlmResponse(
        'AnalyzeDescriptiveAltText',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.DescriptiveAltTextReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeEEAT(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): partial_types.EEATReport {
    try {
      return this.runtime.parseLlmResponse(
        'AnalyzeEEAT',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.EEATReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeFAQSchemaMarkup(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): partial_types.FAQSchemaMarkupReport {
    try {
      return this.runtime.parseLlmResponse(
        'AnalyzeFAQSchemaMarkup',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.FAQSchemaMarkupReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeFormAccessibility(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): partial_types.FormAccessibilityReport {
    try {
      return this.runtime.parseLlmResponse(
        'AnalyzeFormAccessibility',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.FormAccessibilityReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeH1Tag(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): partial_types.H1TagReport {
    try {
      return this.runtime.parseLlmResponse(
        'AnalyzeH1Tag',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.H1TagReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeHeadingHierarchy(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): partial_types.HeadingHierarchyReport {
    try {
      return this.runtime.parseLlmResponse(
        'AnalyzeHeadingHierarchy',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.HeadingHierarchyReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeHeadingStructure(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): partial_types.HeadingStructureReport {
    try {
      return this.runtime.parseLlmResponse(
        'AnalyzeHeadingStructure',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.HeadingStructureReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeKeyboardAccessibility(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): partial_types.KeyboardAccessibilityReport {
    try {
      return this.runtime.parseLlmResponse(
        'AnalyzeKeyboardAccessibility',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.KeyboardAccessibilityReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeMainSections(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): partial_types.MainSectionsReport {
    try {
      return this.runtime.parseLlmResponse(
        'AnalyzeMainSections',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.MainSectionsReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeSemanticElements(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): partial_types.SemanticElementsReport {
    try {
      return this.runtime.parseLlmResponse(
        'AnalyzeSemanticElements',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.SemanticElementsReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeSemanticTags(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): partial_types.SemanticTagReport {
    try {
      return this.runtime.parseLlmResponse(
        'AnalyzeSemanticTags',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.SemanticTagReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeUserIntent(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): partial_types.UserIntentReport {
    try {
      return this.runtime.parseLlmResponse(
        'AnalyzeUserIntent',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.UserIntentReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeWebsiteScreenshot(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): partial_types.WebsiteScreenshotAnalysis {
    try {
      return this.runtime.parseLlmResponse(
        'AnalyzeWebsiteScreenshot',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.WebsiteScreenshotAnalysis;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AssessWebpageImages(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): partial_types.WebpageImagesReport {
    try {
      return this.runtime.parseLlmResponse(
        'AssessWebpageImages',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.WebpageImagesReport;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  ExtractSEOMetadata(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): partial_types.SEOMetadata {
    try {
      return this.runtime.parseLlmResponse(
        'ExtractSEOMetadata',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.SEOMetadata;
    } catch (error) {
      throw toBamlError(error);
    }
  }

  SuggestImprovements(
    llmResponse: string,
    __baml_options__?: { tb?: TypeBuilder; clientRegistry?: ClientRegistry },
  ): partial_types.ImprovementSuggestions {
    try {
      return this.runtime.parseLlmResponse(
        'SuggestImprovements',
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.ImprovementSuggestions;
    } catch (error) {
      throw toBamlError(error);
    }
  }
}
