/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { BamlCtxManager, BamlRuntime, ClientRegistry, Image, } from "@boundaryml/baml"
import { type HTTPRequest, toBamlError } from '@boundaryml/baml';
import type TypeBuilder from './type_builder';
import type {
  AccessibilityReport,
  ContentStructure,
  SEOMetadata,
} from './types';

type BamlCallOptions = {
  tb?: TypeBuilder;
  clientRegistry?: ClientRegistry;
};

export class HttpRequest {
  constructor(
    private runtime: BamlRuntime,
    private ctxManager: BamlCtxManager,
  ) {}

  AnalyzeAccessibility(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        'AnalyzeAccessibility',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeAltText(img: Image, __baml_options__?: BamlCallOptions): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        'AnalyzeAltText',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeArticleSchemaMarkup(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        'AnalyzeArticleSchemaMarkup',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeContentClarity(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        'AnalyzeContentClarity',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeContentStructure(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        'AnalyzeContentStructure',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeContrast(img: Image, __baml_options__?: BamlCallOptions): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        'AnalyzeContrast',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeDescriptiveAltText(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        'AnalyzeDescriptiveAltText',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeEEAT(img: Image, __baml_options__?: BamlCallOptions): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        'AnalyzeEEAT',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeFAQSchemaMarkup(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        'AnalyzeFAQSchemaMarkup',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeFormAccessibility(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        'AnalyzeFormAccessibility',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeH1Tag(img: Image, __baml_options__?: BamlCallOptions): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        'AnalyzeH1Tag',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeHeadingHierarchy(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        'AnalyzeHeadingHierarchy',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeHeadingStructure(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        'AnalyzeHeadingStructure',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeKeyboardAccessibility(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        'AnalyzeKeyboardAccessibility',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeMainSections(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        'AnalyzeMainSections',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeSemanticElements(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        'AnalyzeSemanticElements',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeSemanticTags(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        'AnalyzeSemanticTags',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeUserIntent(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        'AnalyzeUserIntent',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeWebsiteScreenshot(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        'AnalyzeWebsiteScreenshot',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AssessWebpageImages(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        'AssessWebpageImages',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  ExtractSEOMetadata(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        'ExtractSEOMetadata',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  SuggestImprovements(
    seo: SEOMetadata,
    accessibility: AccessibilityReport,
    structure: ContentStructure,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        'SuggestImprovements',
        {
          seo: seo,
          accessibility: accessibility,
          structure: structure,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }
}

export class HttpStreamRequest {
  constructor(
    private runtime: BamlRuntime,
    private ctxManager: BamlCtxManager,
  ) {}

  AnalyzeAccessibility(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        'AnalyzeAccessibility',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeAltText(img: Image, __baml_options__?: BamlCallOptions): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        'AnalyzeAltText',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeArticleSchemaMarkup(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        'AnalyzeArticleSchemaMarkup',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeContentClarity(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        'AnalyzeContentClarity',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeContentStructure(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        'AnalyzeContentStructure',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeContrast(img: Image, __baml_options__?: BamlCallOptions): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        'AnalyzeContrast',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeDescriptiveAltText(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        'AnalyzeDescriptiveAltText',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeEEAT(img: Image, __baml_options__?: BamlCallOptions): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        'AnalyzeEEAT',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeFAQSchemaMarkup(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        'AnalyzeFAQSchemaMarkup',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeFormAccessibility(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        'AnalyzeFormAccessibility',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeH1Tag(img: Image, __baml_options__?: BamlCallOptions): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        'AnalyzeH1Tag',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeHeadingHierarchy(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        'AnalyzeHeadingHierarchy',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeHeadingStructure(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        'AnalyzeHeadingStructure',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeKeyboardAccessibility(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        'AnalyzeKeyboardAccessibility',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeMainSections(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        'AnalyzeMainSections',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeSemanticElements(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        'AnalyzeSemanticElements',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeSemanticTags(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        'AnalyzeSemanticTags',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeUserIntent(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        'AnalyzeUserIntent',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AnalyzeWebsiteScreenshot(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        'AnalyzeWebsiteScreenshot',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  AssessWebpageImages(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        'AssessWebpageImages',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  ExtractSEOMetadata(
    img: Image,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        'ExtractSEOMetadata',
        {
          img: img,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }

  SuggestImprovements(
    seo: SEOMetadata,
    accessibility: AccessibilityReport,
    structure: ContentStructure,
    __baml_options__?: BamlCallOptions,
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        'SuggestImprovements',
        {
          seo: seo,
          accessibility: accessibility,
          structure: structure,
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      );
    } catch (error) {
      throw toBamlError(error);
    }
  }
}
