/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { FieldType } from '@boundaryml/baml/native'
import {
  type ClassBuilder,
  type ClassViewer,
  type EnumBuilder,
  TypeBuilder as _TypeBuilder,
} from '@boundaryml/baml/type_builder';
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from './globals';

export default class TypeBuilder {
  private tb: _TypeBuilder;

  AccessibilityReport: ClassViewer<
    'AccessibilityReport',
    'missing_alt_text' | 'contrast_issues' | 'aria_labels_missing' | 'summary'
  >;

  AltTextReport: ClassViewer<
    'AltTextReport',
    | 'missing_alt_text'
    | 'non_descriptive_alt_text'
    | 'affected_images'
    | 'suggestions'
    | 'summary'
  >;

  ArticleSchemaMarkupReport: ClassViewer<
    'ArticleSchemaMarkupReport',
    | 'schema_present'
    | 'missing_properties'
    | 'recommendation'
    | 'benefit_for_llms'
    | 'example'
    | 'summary'
  >;

  ContentClarityReport: ClassViewer<
    'ContentClarityReport',
    | 'complex_language'
    | 'verbose_sections'
    | 'recommendation'
    | 'benefit_for_llms'
    | 'summary'
  >;

  ContentStructure: ClassViewer<
    'ContentStructure',
    'headings' | 'semantic_tags' | 'main_sections'
  >;

  ContrastReport: ClassViewer<
    'ContrastReport',
    'contrast_issues' | 'contrast_ratios' | 'suggestions' | 'summary'
  >;

  DescriptiveAltTextReport: ClassViewer<
    'DescriptiveAltTextReport',
    | 'missing_alt_text'
    | 'non_descriptive_alt_text'
    | 'affected_images'
    | 'recommendation'
    | 'benefit_for_llms'
    | 'summary'
  >;

  EEATReport: ClassViewer<
    'EEATReport',
    | 'author_expertise'
    | 'credible_sources'
    | 'factual_accuracy'
    | 'contact_info_present'
    | 'https_enabled'
    | 'missing_signals'
    | 'recommendation'
    | 'benefit_for_llms'
    | 'summary'
  >;

  FAQSchemaMarkupReport: ClassViewer<
    'FAQSchemaMarkupReport',
    | 'schema_present'
    | 'question_answer_pairs'
    | 'recommendation'
    | 'benefit_for_llms'
    | 'example'
    | 'summary'
  >;

  FormAccessibilityReport: ClassViewer<
    'FormAccessibilityReport',
    'form_label_issues' | 'error_message_issues' | 'suggestions' | 'summary'
  >;

  H1TagReport: ClassViewer<
    'H1TagReport',
    | 'h1_present'
    | 'multiple_h1'
    | 'h1_text'
    | 'recommendation'
    | 'benefit_for_llms'
    | 'summary'
  >;

  HeadingHierarchyReport: ClassViewer<
    'HeadingHierarchyReport',
    | 'skipped_levels'
    | 'illogical_structure'
    | 'problematic_headings'
    | 'recommendation'
    | 'benefit_for_llms'
    | 'summary'
  >;

  HeadingStructureReport: ClassViewer<
    'HeadingStructureReport',
    'headings' | 'heading_texts' | 'suggestions' | 'summary'
  >;

  ImageInfo: ClassViewer<
    'ImageInfo',
    'src' | 'alt_text' | 'descriptive' | 'decorative'
  >;

  ImprovementSuggestions: ClassViewer<
    'ImprovementSuggestions',
    'seo' | 'accessibility' | 'performance' | 'overall_priority'
  >;

  KeyboardAccessibilityReport: ClassViewer<
    'KeyboardAccessibilityReport',
    | 'focus_indicators_missing'
    | 'tab_order_issues'
    | 'skip_link_missing'
    | 'suggestions'
    | 'summary'
  >;

  MainSectionsReport: ClassViewer<
    'MainSectionsReport',
    'main_sections' | 'missing_sections' | 'suggestions' | 'summary'
  >;

  SEOMetadata: ClassViewer<
    'SEOMetadata',
    | 'meta_title'
    | 'meta_description'
    | 'canonical_url'
    | 'og_title'
    | 'og_description'
    | 'twitter_card'
  >;

  SemanticElementsReport: ClassViewer<
    'SemanticElementsReport',
    | 'overuse_generic_tags'
    | 'missing_semantic_elements'
    | 'recommendation'
    | 'benefit_for_llms'
    | 'summary'
  >;

  SemanticTagReport: ClassViewer<
    'SemanticTagReport',
    'semantic_tags' | 'missing_semantic_tags' | 'suggestions' | 'summary'
  >;

  UserIntentReport: ClassViewer<
    'UserIntentReport',
    | 'addresses_user_intent'
    | 'missing_intent_areas'
    | 'recommendation'
    | 'benefit_for_llms'
    | 'summary'
  >;

  WebpageImagesReport: ClassViewer<
    'WebpageImagesReport',
    | 'total_images'
    | 'images_info'
    | 'missing_alt_count'
    | 'non_descriptive_alt_count'
    | 'decorative_images'
    | 'recommendation'
    | 'summary'
  >;

  WebsiteScreenshotAnalysis: ClassViewer<
    'WebsiteScreenshotAnalysis',
    'title' | 'main_text' | 'detected_elements' | 'dominant_colors' | 'language'
  >;

  constructor() {
    this.tb = new _TypeBuilder({
      classes: new Set([
        'AccessibilityReport',
        'AltTextReport',
        'ArticleSchemaMarkupReport',
        'ContentClarityReport',
        'ContentStructure',
        'ContrastReport',
        'DescriptiveAltTextReport',
        'EEATReport',
        'FAQSchemaMarkupReport',
        'FormAccessibilityReport',
        'H1TagReport',
        'HeadingHierarchyReport',
        'HeadingStructureReport',
        'ImageInfo',
        'ImprovementSuggestions',
        'KeyboardAccessibilityReport',
        'MainSectionsReport',
        'SEOMetadata',
        'SemanticElementsReport',
        'SemanticTagReport',
        'UserIntentReport',
        'WebpageImagesReport',
        'WebsiteScreenshotAnalysis',
      ]),
      enums: new Set([]),
      runtime: DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME,
    });

    this.AccessibilityReport = this.tb.classViewer('AccessibilityReport', [
      'missing_alt_text',
      'contrast_issues',
      'aria_labels_missing',
      'summary',
    ]);

    this.AltTextReport = this.tb.classViewer('AltTextReport', [
      'missing_alt_text',
      'non_descriptive_alt_text',
      'affected_images',
      'suggestions',
      'summary',
    ]);

    this.ArticleSchemaMarkupReport = this.tb.classViewer(
      'ArticleSchemaMarkupReport',
      [
        'schema_present',
        'missing_properties',
        'recommendation',
        'benefit_for_llms',
        'example',
        'summary',
      ],
    );

    this.ContentClarityReport = this.tb.classViewer('ContentClarityReport', [
      'complex_language',
      'verbose_sections',
      'recommendation',
      'benefit_for_llms',
      'summary',
    ]);

    this.ContentStructure = this.tb.classViewer('ContentStructure', [
      'headings',
      'semantic_tags',
      'main_sections',
    ]);

    this.ContrastReport = this.tb.classViewer('ContrastReport', [
      'contrast_issues',
      'contrast_ratios',
      'suggestions',
      'summary',
    ]);

    this.DescriptiveAltTextReport = this.tb.classViewer(
      'DescriptiveAltTextReport',
      [
        'missing_alt_text',
        'non_descriptive_alt_text',
        'affected_images',
        'recommendation',
        'benefit_for_llms',
        'summary',
      ],
    );

    this.EEATReport = this.tb.classViewer('EEATReport', [
      'author_expertise',
      'credible_sources',
      'factual_accuracy',
      'contact_info_present',
      'https_enabled',
      'missing_signals',
      'recommendation',
      'benefit_for_llms',
      'summary',
    ]);

    this.FAQSchemaMarkupReport = this.tb.classViewer('FAQSchemaMarkupReport', [
      'schema_present',
      'question_answer_pairs',
      'recommendation',
      'benefit_for_llms',
      'example',
      'summary',
    ]);

    this.FormAccessibilityReport = this.tb.classViewer(
      'FormAccessibilityReport',
      ['form_label_issues', 'error_message_issues', 'suggestions', 'summary'],
    );

    this.H1TagReport = this.tb.classViewer('H1TagReport', [
      'h1_present',
      'multiple_h1',
      'h1_text',
      'recommendation',
      'benefit_for_llms',
      'summary',
    ]);

    this.HeadingHierarchyReport = this.tb.classViewer(
      'HeadingHierarchyReport',
      [
        'skipped_levels',
        'illogical_structure',
        'problematic_headings',
        'recommendation',
        'benefit_for_llms',
        'summary',
      ],
    );

    this.HeadingStructureReport = this.tb.classViewer(
      'HeadingStructureReport',
      ['headings', 'heading_texts', 'suggestions', 'summary'],
    );

    this.ImageInfo = this.tb.classViewer('ImageInfo', [
      'src',
      'alt_text',
      'descriptive',
      'decorative',
    ]);

    this.ImprovementSuggestions = this.tb.classViewer(
      'ImprovementSuggestions',
      ['seo', 'accessibility', 'performance', 'overall_priority'],
    );

    this.KeyboardAccessibilityReport = this.tb.classViewer(
      'KeyboardAccessibilityReport',
      [
        'focus_indicators_missing',
        'tab_order_issues',
        'skip_link_missing',
        'suggestions',
        'summary',
      ],
    );

    this.MainSectionsReport = this.tb.classViewer('MainSectionsReport', [
      'main_sections',
      'missing_sections',
      'suggestions',
      'summary',
    ]);

    this.SEOMetadata = this.tb.classViewer('SEOMetadata', [
      'meta_title',
      'meta_description',
      'canonical_url',
      'og_title',
      'og_description',
      'twitter_card',
    ]);

    this.SemanticElementsReport = this.tb.classViewer(
      'SemanticElementsReport',
      [
        'overuse_generic_tags',
        'missing_semantic_elements',
        'recommendation',
        'benefit_for_llms',
        'summary',
      ],
    );

    this.SemanticTagReport = this.tb.classViewer('SemanticTagReport', [
      'semantic_tags',
      'missing_semantic_tags',
      'suggestions',
      'summary',
    ]);

    this.UserIntentReport = this.tb.classViewer('UserIntentReport', [
      'addresses_user_intent',
      'missing_intent_areas',
      'recommendation',
      'benefit_for_llms',
      'summary',
    ]);

    this.WebpageImagesReport = this.tb.classViewer('WebpageImagesReport', [
      'total_images',
      'images_info',
      'missing_alt_count',
      'non_descriptive_alt_count',
      'decorative_images',
      'recommendation',
      'summary',
    ]);

    this.WebsiteScreenshotAnalysis = this.tb.classViewer(
      'WebsiteScreenshotAnalysis',
      [
        'title',
        'main_text',
        'detected_elements',
        'dominant_colors',
        'language',
      ],
    );
  }

  __tb() {
    return this.tb._tb();
  }

  string(): FieldType {
    return this.tb.string();
  }

  literalString(value: string): FieldType {
    return this.tb.literalString(value);
  }

  literalInt(value: number): FieldType {
    return this.tb.literalInt(value);
  }

  literalBool(value: boolean): FieldType {
    return this.tb.literalBool(value);
  }

  int(): FieldType {
    return this.tb.int();
  }

  float(): FieldType {
    return this.tb.float();
  }

  bool(): FieldType {
    return this.tb.bool();
  }

  list(type: FieldType): FieldType {
    return this.tb.list(type);
  }

  null(): FieldType {
    return this.tb.null();
  }

  map(key: FieldType, value: FieldType): FieldType {
    return this.tb.map(key, value);
  }

  union(types: FieldType[]): FieldType {
    return this.tb.union(types);
  }

  addClass<Name extends string>(name: Name): ClassBuilder<Name> {
    return this.tb.addClass(name);
  }

  addEnum<Name extends string>(name: Name): EnumBuilder<Name> {
    return this.tb.addEnum(name);
  }

  addBaml(baml: string): void {
    this.tb.addBaml(baml);
  }
}
