/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
'use server'

import type { Image } from '@boundaryml/baml';
import { b } from '../index';

import type {
  AccessibilityReport,
  ContentStructure,
  SEOMetadata,
} from '../types';

/**
 * Streaming BAML server actions that return ReadableStreams.
 */

/**
 * Executes the streaming variant of the "AnalyzeAccessibility" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { Image } img - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const AnalyzeAccessibility = async (
  img: Image,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.AnalyzeAccessibility(img);
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "AnalyzeAltText" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { Image } img - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const AnalyzeAltText = async (
  img: Image,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.AnalyzeAltText(img);
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "AnalyzeArticleSchemaMarkup" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { Image } img - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const AnalyzeArticleSchemaMarkup = async (
  img: Image,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.AnalyzeArticleSchemaMarkup(img);
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "AnalyzeContentClarity" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { Image } img - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const AnalyzeContentClarity = async (
  img: Image,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.AnalyzeContentClarity(img);
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "AnalyzeContentStructure" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { Image } img - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const AnalyzeContentStructure = async (
  img: Image,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.AnalyzeContentStructure(img);
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "AnalyzeContrast" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { Image } img - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const AnalyzeContrast = async (
  img: Image,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.AnalyzeContrast(img);
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "AnalyzeDescriptiveAltText" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { Image } img - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const AnalyzeDescriptiveAltText = async (
  img: Image,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.AnalyzeDescriptiveAltText(img);
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "AnalyzeEEAT" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { Image } img - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const AnalyzeEEAT = async (
  img: Image,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.AnalyzeEEAT(img);
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "AnalyzeFAQSchemaMarkup" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { Image } img - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const AnalyzeFAQSchemaMarkup = async (
  img: Image,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.AnalyzeFAQSchemaMarkup(img);
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "AnalyzeFormAccessibility" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { Image } img - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const AnalyzeFormAccessibility = async (
  img: Image,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.AnalyzeFormAccessibility(img);
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "AnalyzeH1Tag" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { Image } img - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const AnalyzeH1Tag = async (
  img: Image,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.AnalyzeH1Tag(img);
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "AnalyzeHeadingHierarchy" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { Image } img - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const AnalyzeHeadingHierarchy = async (
  img: Image,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.AnalyzeHeadingHierarchy(img);
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "AnalyzeHeadingStructure" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { Image } img - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const AnalyzeHeadingStructure = async (
  img: Image,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.AnalyzeHeadingStructure(img);
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "AnalyzeKeyboardAccessibility" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { Image } img - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const AnalyzeKeyboardAccessibility = async (
  img: Image,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.AnalyzeKeyboardAccessibility(img);
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "AnalyzeMainSections" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { Image } img - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const AnalyzeMainSections = async (
  img: Image,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.AnalyzeMainSections(img);
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "AnalyzeSemanticElements" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { Image } img - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const AnalyzeSemanticElements = async (
  img: Image,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.AnalyzeSemanticElements(img);
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "AnalyzeSemanticTags" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { Image } img - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const AnalyzeSemanticTags = async (
  img: Image,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.AnalyzeSemanticTags(img);
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "AnalyzeUserIntent" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { Image } img - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const AnalyzeUserIntent = async (
  img: Image,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.AnalyzeUserIntent(img);
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "AnalyzeWebsiteScreenshot" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { Image } img - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const AnalyzeWebsiteScreenshot = async (
  img: Image,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.AnalyzeWebsiteScreenshot(img);
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "AssessWebpageImages" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { Image } img - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const AssessWebpageImages = async (
  img: Image,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.AssessWebpageImages(img);
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "ExtractSEOMetadata" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { Image } img - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const ExtractSEOMetadata = async (
  img: Image,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.ExtractSEOMetadata(img);
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "SuggestImprovements" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { SEOMetadata } seo - Input parameter.
 * @param { AccessibilityReport } accessibility - Input parameter.
 * @param { ContentStructure } structure - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const SuggestImprovements = async (
  seo: SEOMetadata,
  accessibility: AccessibilityReport,
  structure: ContentStructure,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.SuggestImprovements(seo, accessibility, structure);
  return Promise.resolve(stream.toStreamable());
};
