/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
'use server'

import type { Image } from '@boundaryml/baml';
import { b } from '../index';

import type {
  AccessibilityReport,
  AltTextReport,
  ArticleSchemaMarkupReport,
  ContentClarityReport,
  ContentStructure,
  ContrastReport,
  DescriptiveAltTextReport,
  EEATReport,
  FAQSchemaMarkupReport,
  FormAccessibilityReport,
  H1TagReport,
  HeadingHierarchyReport,
  HeadingStructureReport,
  ImprovementSuggestions,
  KeyboardAccessibilityReport,
  MainSectionsReport,
  SEOMetadata,
  SemanticElementsReport,
  SemanticTagReport,
  UserIntentReport,
  WebpageImagesReport,
  WebsiteScreenshotAnalysis,
} from '../types';

/**
 * Regular BAML server actions that return direct responses.
 */

/**
 * Executes the "AnalyzeAccessibility" BAML action.
 *
 * This server action calls the underlying BAML function "AnalyzeAccessibility"
 * with the specified parameters.
 *
 * @param { Image } img - Input parameter.
 *
 * @returns {Promise<AccessibilityReport>} A promise that resolves with the result of the action.
 */
export const AnalyzeAccessibility = async (
  img: Image,
): Promise<AccessibilityReport> => {
  return b.AnalyzeAccessibility(img);
};

/**
 * Executes the "AnalyzeAltText" BAML action.
 *
 * This server action calls the underlying BAML function "AnalyzeAltText"
 * with the specified parameters.
 *
 * @param { Image } img - Input parameter.
 *
 * @returns {Promise<AltTextReport>} A promise that resolves with the result of the action.
 */
export const AnalyzeAltText = async (img: Image): Promise<AltTextReport> => {
  return b.AnalyzeAltText(img);
};

/**
 * Executes the "AnalyzeArticleSchemaMarkup" BAML action.
 *
 * This server action calls the underlying BAML function "AnalyzeArticleSchemaMarkup"
 * with the specified parameters.
 *
 * @param { Image } img - Input parameter.
 *
 * @returns {Promise<ArticleSchemaMarkupReport>} A promise that resolves with the result of the action.
 */
export const AnalyzeArticleSchemaMarkup = async (
  img: Image,
): Promise<ArticleSchemaMarkupReport> => {
  return b.AnalyzeArticleSchemaMarkup(img);
};

/**
 * Executes the "AnalyzeContentClarity" BAML action.
 *
 * This server action calls the underlying BAML function "AnalyzeContentClarity"
 * with the specified parameters.
 *
 * @param { Image } img - Input parameter.
 *
 * @returns {Promise<ContentClarityReport>} A promise that resolves with the result of the action.
 */
export const AnalyzeContentClarity = async (
  img: Image,
): Promise<ContentClarityReport> => {
  return b.AnalyzeContentClarity(img);
};

/**
 * Executes the "AnalyzeContentStructure" BAML action.
 *
 * This server action calls the underlying BAML function "AnalyzeContentStructure"
 * with the specified parameters.
 *
 * @param { Image } img - Input parameter.
 *
 * @returns {Promise<ContentStructure>} A promise that resolves with the result of the action.
 */
export const AnalyzeContentStructure = async (
  img: Image,
): Promise<ContentStructure> => {
  return b.AnalyzeContentStructure(img);
};

/**
 * Executes the "AnalyzeContrast" BAML action.
 *
 * This server action calls the underlying BAML function "AnalyzeContrast"
 * with the specified parameters.
 *
 * @param { Image } img - Input parameter.
 *
 * @returns {Promise<ContrastReport>} A promise that resolves with the result of the action.
 */
export const AnalyzeContrast = async (img: Image): Promise<ContrastReport> => {
  return b.AnalyzeContrast(img);
};

/**
 * Executes the "AnalyzeDescriptiveAltText" BAML action.
 *
 * This server action calls the underlying BAML function "AnalyzeDescriptiveAltText"
 * with the specified parameters.
 *
 * @param { Image } img - Input parameter.
 *
 * @returns {Promise<DescriptiveAltTextReport>} A promise that resolves with the result of the action.
 */
export const AnalyzeDescriptiveAltText = async (
  img: Image,
): Promise<DescriptiveAltTextReport> => {
  return b.AnalyzeDescriptiveAltText(img);
};

/**
 * Executes the "AnalyzeEEAT" BAML action.
 *
 * This server action calls the underlying BAML function "AnalyzeEEAT"
 * with the specified parameters.
 *
 * @param { Image } img - Input parameter.
 *
 * @returns {Promise<EEATReport>} A promise that resolves with the result of the action.
 */
export const AnalyzeEEAT = async (img: Image): Promise<EEATReport> => {
  return b.AnalyzeEEAT(img);
};

/**
 * Executes the "AnalyzeFAQSchemaMarkup" BAML action.
 *
 * This server action calls the underlying BAML function "AnalyzeFAQSchemaMarkup"
 * with the specified parameters.
 *
 * @param { Image } img - Input parameter.
 *
 * @returns {Promise<FAQSchemaMarkupReport>} A promise that resolves with the result of the action.
 */
export const AnalyzeFAQSchemaMarkup = async (
  img: Image,
): Promise<FAQSchemaMarkupReport> => {
  return b.AnalyzeFAQSchemaMarkup(img);
};

/**
 * Executes the "AnalyzeFormAccessibility" BAML action.
 *
 * This server action calls the underlying BAML function "AnalyzeFormAccessibility"
 * with the specified parameters.
 *
 * @param { Image } img - Input parameter.
 *
 * @returns {Promise<FormAccessibilityReport>} A promise that resolves with the result of the action.
 */
export const AnalyzeFormAccessibility = async (
  img: Image,
): Promise<FormAccessibilityReport> => {
  return b.AnalyzeFormAccessibility(img);
};

/**
 * Executes the "AnalyzeH1Tag" BAML action.
 *
 * This server action calls the underlying BAML function "AnalyzeH1Tag"
 * with the specified parameters.
 *
 * @param { Image } img - Input parameter.
 *
 * @returns {Promise<H1TagReport>} A promise that resolves with the result of the action.
 */
export const AnalyzeH1Tag = async (img: Image): Promise<H1TagReport> => {
  return b.AnalyzeH1Tag(img);
};

/**
 * Executes the "AnalyzeHeadingHierarchy" BAML action.
 *
 * This server action calls the underlying BAML function "AnalyzeHeadingHierarchy"
 * with the specified parameters.
 *
 * @param { Image } img - Input parameter.
 *
 * @returns {Promise<HeadingHierarchyReport>} A promise that resolves with the result of the action.
 */
export const AnalyzeHeadingHierarchy = async (
  img: Image,
): Promise<HeadingHierarchyReport> => {
  return b.AnalyzeHeadingHierarchy(img);
};

/**
 * Executes the "AnalyzeHeadingStructure" BAML action.
 *
 * This server action calls the underlying BAML function "AnalyzeHeadingStructure"
 * with the specified parameters.
 *
 * @param { Image } img - Input parameter.
 *
 * @returns {Promise<HeadingStructureReport>} A promise that resolves with the result of the action.
 */
export const AnalyzeHeadingStructure = async (
  img: Image,
): Promise<HeadingStructureReport> => {
  return b.AnalyzeHeadingStructure(img);
};

/**
 * Executes the "AnalyzeKeyboardAccessibility" BAML action.
 *
 * This server action calls the underlying BAML function "AnalyzeKeyboardAccessibility"
 * with the specified parameters.
 *
 * @param { Image } img - Input parameter.
 *
 * @returns {Promise<KeyboardAccessibilityReport>} A promise that resolves with the result of the action.
 */
export const AnalyzeKeyboardAccessibility = async (
  img: Image,
): Promise<KeyboardAccessibilityReport> => {
  return b.AnalyzeKeyboardAccessibility(img);
};

/**
 * Executes the "AnalyzeMainSections" BAML action.
 *
 * This server action calls the underlying BAML function "AnalyzeMainSections"
 * with the specified parameters.
 *
 * @param { Image } img - Input parameter.
 *
 * @returns {Promise<MainSectionsReport>} A promise that resolves with the result of the action.
 */
export const AnalyzeMainSections = async (
  img: Image,
): Promise<MainSectionsReport> => {
  return b.AnalyzeMainSections(img);
};

/**
 * Executes the "AnalyzeSemanticElements" BAML action.
 *
 * This server action calls the underlying BAML function "AnalyzeSemanticElements"
 * with the specified parameters.
 *
 * @param { Image } img - Input parameter.
 *
 * @returns {Promise<SemanticElementsReport>} A promise that resolves with the result of the action.
 */
export const AnalyzeSemanticElements = async (
  img: Image,
): Promise<SemanticElementsReport> => {
  return b.AnalyzeSemanticElements(img);
};

/**
 * Executes the "AnalyzeSemanticTags" BAML action.
 *
 * This server action calls the underlying BAML function "AnalyzeSemanticTags"
 * with the specified parameters.
 *
 * @param { Image } img - Input parameter.
 *
 * @returns {Promise<SemanticTagReport>} A promise that resolves with the result of the action.
 */
export const AnalyzeSemanticTags = async (
  img: Image,
): Promise<SemanticTagReport> => {
  return b.AnalyzeSemanticTags(img);
};

/**
 * Executes the "AnalyzeUserIntent" BAML action.
 *
 * This server action calls the underlying BAML function "AnalyzeUserIntent"
 * with the specified parameters.
 *
 * @param { Image } img - Input parameter.
 *
 * @returns {Promise<UserIntentReport>} A promise that resolves with the result of the action.
 */
export const AnalyzeUserIntent = async (
  img: Image,
): Promise<UserIntentReport> => {
  return b.AnalyzeUserIntent(img);
};

/**
 * Executes the "AnalyzeWebsiteScreenshot" BAML action.
 *
 * This server action calls the underlying BAML function "AnalyzeWebsiteScreenshot"
 * with the specified parameters.
 *
 * @param { Image } img - Input parameter.
 *
 * @returns {Promise<WebsiteScreenshotAnalysis>} A promise that resolves with the result of the action.
 */
export const AnalyzeWebsiteScreenshot = async (
  img: Image,
): Promise<WebsiteScreenshotAnalysis> => {
  return b.AnalyzeWebsiteScreenshot(img);
};

/**
 * Executes the "AssessWebpageImages" BAML action.
 *
 * This server action calls the underlying BAML function "AssessWebpageImages"
 * with the specified parameters.
 *
 * @param { Image } img - Input parameter.
 *
 * @returns {Promise<WebpageImagesReport>} A promise that resolves with the result of the action.
 */
export const AssessWebpageImages = async (
  img: Image,
): Promise<WebpageImagesReport> => {
  return b.AssessWebpageImages(img);
};

/**
 * Executes the "ExtractSEOMetadata" BAML action.
 *
 * This server action calls the underlying BAML function "ExtractSEOMetadata"
 * with the specified parameters.
 *
 * @param { Image } img - Input parameter.
 *
 * @returns {Promise<SEOMetadata>} A promise that resolves with the result of the action.
 */
export const ExtractSEOMetadata = async (img: Image): Promise<SEOMetadata> => {
  return b.ExtractSEOMetadata(img);
};

/**
 * Executes the "SuggestImprovements" BAML action.
 *
 * This server action calls the underlying BAML function "SuggestImprovements"
 * with the specified parameters.
 *
 * @param { SEOMetadata } seo - Input parameter.
 * @param { AccessibilityReport } accessibility - Input parameter.
 * @param { ContentStructure } structure - Input parameter.
 *
 * @returns {Promise<ImprovementSuggestions>} A promise that resolves with the result of the action.
 */
export const SuggestImprovements = async (
  seo: SEOMetadata,
  accessibility: AccessibilityReport,
  structure: ContentStructure,
): Promise<ImprovementSuggestions> => {
  return b.SuggestImprovements(seo, accessibility, structure);
};
